import { useState } from "react";
import { ArrowLeft, Mail, Lock, UserRound, ArrowRight } from "lucide-react";
import { supabase } from "@/lib/supabase";

export default function Auth({ onComplete }: { onComplete: (name: string) => void }) {
  const [mode, setMode] = useState<"signin" | "signup">("signup");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError("");
    if (supabase) { const result = mode === "signup" ? await supabase.auth.signUp({ email, password, options: { data: { name } } }) : await supabase.auth.signInWithPassword({ email, password }); if (result.error) { setError(result.error.message); setBusy(false); return; } }
    localStorage.setItem("citycab_session", "active"); localStorage.setItem("citycab_name", name || email.split("@")[0]); onComplete(name || email.split("@")[0]); setBusy(false);
  };
  return <main className="safe-page min-h-screen bg-background px-5 py-6"><div className="mx-auto flex min-h-[calc(100vh-3rem)] max-w-md flex-col"><button onClick={() => setMode("signup")} className="flex h-10 w-10 items-center justify-center rounded-xl bg-card text-primary shadow-sm"><ArrowLeft className="h-5 w-5" /></button><div className="mt-12"><p className="text-xs font-black uppercase tracking-[0.18em] text-accent">Windhoek City Cab</p><h1 className="mt-3 text-4xl font-black leading-tight text-primary">{mode === "signup" ? "Create your account" : "Welcome back"}</h1><p className="mt-3 text-sm font-medium text-muted-foreground">{mode === "signup" ? "Save your places and manage every ride in one place." : "Sign in to continue your journey."}</p></div><form onSubmit={submit} className="mt-9 space-y-3">{mode === "signup" && <Field icon={<UserRound />} value={name} onChange={setName} placeholder="Full name" />}<Field icon={<Mail />} value={email} onChange={setEmail} placeholder="Email address" type="email" /><Field icon={<Lock />} value={password} onChange={setPassword} placeholder="Password" type="password" />{error && <p className="rounded-xl bg-destructive/10 p-3 text-xs font-bold text-destructive">{error}</p>}<button disabled={busy} className="mt-3 flex h-14 w-full items-center justify-center gap-2 rounded-2xl bg-accent text-base font-black text-accent-foreground disabled:opacity-60">{busy ? "Please wait..." : mode === "signup" ? "Create account" : "Sign in"}<ArrowRight className="h-5 w-5" /></button></form><button onClick={() => setMode(mode === "signup" ? "signin" : "signup")} className="mt-auto pt-8 text-center text-sm font-bold text-muted-foreground">{mode === "signup" ? "Already have an account? " : "New to City Cab? "}<span className="text-accent">{mode === "signup" ? "Sign in" : "Create an account"}</span></button></div></main>;
}
function Field({ icon, value, onChange, placeholder, type = "text" }: { icon: React.ReactNode; value: string; onChange: (value: string) => void; placeholder: string; type?: string }) { return <label className="flex h-14 items-center gap-3 rounded-2xl border border-border bg-card px-4"><span className="text-accent">{icon}</span><input required type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="min-w-0 flex-1 bg-transparent text-sm font-bold text-primary outline-none placeholder:text-muted-foreground" /></label>; }
